const books = [
    {
        title: "The Alchemist",
        author: "Paulo Coelho",
        year: 1988,
        description: "A journey of self-discovery and destiny.",
        price: 9.99,
        genre: "Adventure",
        image: "img/alchemist.jpg",
    },
    {
        title: "1984",
        author: "George Orwell",
        year: 1949,
        description: "A dystopian future ruled by totalitarianism.",
        price: 8.49,
        genre: "Dystopian",
        image: "img/1984.jpg",
    },
    {
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        year: 1960,
        description: "A novel about racial injustice in the Deep South.",
        price: 7.99,
        genre: "Fiction",
        image: "img/mockingbird.jpg",
    },
    {
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        year: 1925,
        description: "A story about the American dream and its disillusionment.",
        price: 10.50,
        genre: "Classic",
        image: "img/gatsby.jpg",
    },
    {
        title: "Moby-Dick",
        author: "Herman Melville",
        year: 1851,
        description: "The voyage of the whaling ship Pequod and its captain, Ahab.",
        price: 11.99,
        genre: "Adventure",
        image: "img/mobydick.jpg",
    },
    {
        title: "Pride and Prejudice",
        author: "Jane Austen",
        year: 1813,
        description: "A classic novel of manners and love in Regency-era England.",
        price: 6.50,
        genre: "Romance",
        image: "img/pandp.jpg",
    },
    {
        title: "War and Peace",
        author: "Leo Tolstoy",
        year: 1869,
        description: "A historical novel set during the Napoleonic Wars.",
        price: 14.99,
        genre: "Historical Fiction",
        image: "img/warandpeace.jpg",
    },
    {
        title: "The Catcher in the Rye",
        author: "J.D. Salinger",
        year: 1951,
        description: "A novel about teenage angst and alienation.",
        price: 9.49,
        genre: "Fiction",
        image: "img/catcher.jpg",
    },
    {
        title: "The Odyssey",
        author: "Homer",
        year: "8th century BC",
        description: "The epic journey of Odysseus as he returns home from the Trojan War.",
        price: 12.99,
        genre: "Epic Poetry",
        image: "img/odyssey.jpg",
    },
    {
        title: "Brave New World",
        author: "Aldous Huxley",
        year: 1932,
        description: "A dystopian novel about a futuristic society based on total control and technology.",
        price: 7.75,
        genre: "Science Fiction",
        image: "img/bnw.jpg",
    }
];
